# id сервера eureka, приложения, где будет запускаться
spring:
  application:
    name: "phone-notification-service"
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST_NAME:localhost}:8888

# куда будет проходить регистрация микросервисов
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"



