# Устанавливаем ноль, чтобы автоматически присваивался порт
server:
  port: 8761

# id сервера eureka, приложения, где будет запускаться
spring:
  application:
    name: "eserver"

# куда будет проходить регистрация микросервисов
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    # У сервера eureka убираем настройки клиентов (микросервисов)
    fetch-registry: false
    register-with-eureka: false

  # Убираем лишние логи
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


